export const possibleCitys = [
    "Tokyo",
    "New York",
    "London",
    "Paris",
    "Hong Kong",
    "Los Angeles",
    "Chicago",
    "Singapore",
    "Beijing",
    "Shanghai",
    "Moscow",
    "Mumbai",
    "Seoul",
    "São Paulo",
    "Mexico City",
    "Dubai",
    "Istanbul",
    "Sydney",
    "Bangkok",
    "Berlin",
    "Rome",
    "Buenos Aires",
    "Toronto",
    "Madrid",
    "Jakarta",
    "Cairo",
    "Kuala Lumpur",
    "Rio de Janeiro",
    "Lagos",
    "Delhi",
    "San Francisco",
    "Miami",
    "Melbourne",
    "Johannesburg",
    "Lima",
    "Bangalore",
    "Karachi",
    "Vienna",
    "Barcelona",
    "Manila",
    "Brussels",
    "Stockholm",
    "Zurich",
    "Amsterdam",
    "Warsaw",
    "Osaka",
    "Lisbon",
    "Athens",
    "Munich",
    "Prague",
    "Montreal",
    "Hanoi",
    "Santiago",
    "Cologne",
    "Budapest",
    "Addis Ababa",
    "Birmingham",
    "Phoenix",
    "Nairobi",
    "Calgary",
    "Pittsburgh",
    "Tunis",
    "Detroit",
    "Tel Aviv",
    "Düsseldorf",
    "Chennai",
    "Tashkent",
    "Reykjavik",
    "Belfast",
    "Lille",
    "Helsinki",
    "Brisbane",
    "Dakar",
    "Bordeaux",
    "Salvador",
    "Valencia",
    "Porto",
    "Catania",
    "Nice",
    "Marseille",
    "Naples",
    "Minsk",
    "Sofia",
    "Sarajevo",
    "Algiers",
    "San Diego",
    "Las Vegas",
    "Wellington",
    "Oslo",
    "Tbilisi",
    "Tallinn",
    "Kiev",
    "Ankara",
    "Tegucigalpa",
    "Port-au-Prince",
    "Gothenburg",
    "Auckland",
    "Luxembourg City",
    "Nassau",
    "Antwerp",
    "Quebec City",
    "Yerevan",
    "Managua",
    "Malmo",
    "Asunción",
    "La Paz",
    "Kingston",
    "Bamako",
    "Lilongwe",
    "Ulaanbaatar",
    "Kuwait City",
    "Papeete",
    "Santo Domingo",
    "Jeddah",
    "Kigali",
    "San Salvador",
    "Port Moresby",
    "Muscat",
    "Suva",
    "Cotonou",
    "Vancouver",
    "Quito",
    "San José",
    "Riga",
    "Kinshasa",
    "Djibouti",
    "Gaborone",
    "Banjul",
    "Antananarivo",
    "Bratislava",
    "Vaduz",
    "San Marino",
    "Palermo",
    "Montevideo",
    "Canberra",
    "Monaco",
    "Zagreb",
    "Copenhagen",
    "Dublin",
    "Vilnius",
    "Bishkek",
    "Astana",
    "Chisinau",
    "Luanda",
    "Frankfurt",
    "Seville",
    "Glasgow",
    "Edinburgh",
    "Liverpool",
    "Cardiff",
    "Leeds",
    "Manchester",
    "Bradford"
  ]